### ISSUE TITLE
Freeswitch restart - listener does not reconnect

### ISSUE THREAD

**Issue by someother1** [rovellipaolo/FreeSWITCH-Listener#1]
Hi
Great FSListerner, thank you :+1: 
One issue does occur - if the freeswitch gets restarted, no more events will be captured.
It seems the listener is stuck on fs reload (the listener is up & running but doesnt do anymore).
Is there a way to prevent this case, and let the listener reconnect as soon as freeswitch is fully restarted?
Kindly regards

**Comment by someother1** [comment]
nevermind, i got it to work with reconnect with:
```
connection.on(FreeswitchApi.Event.Connection.CLOSED, event => {
      log('fs connection closed')
      setTimeout(() => {
        startJob()
      }, 500)
    })
```
If there is a more accurate version to track und handle reconnects / restarts of freeswitch, i will like to hear about. 
thank you

**Comment by rovellipaolo** [comment]
Sorry for answering you only now. But, yes, you got it right! :)
Actually, you could add listeners for both the `CLOSED` and `ERROR` events.
For example:
```
connection.on(FreeswitchApi.Event.Connection.ERROR, () => {
    Log.e(`Error connecting to FreeSWITCH. Retrying in ${RETRY_TIMEOUT_IN_MILLIS} millis...`);
    setTimeout(startJob, RETRY_TIMEOUT_IN_MILLIS);
});

connection.on(FreeswitchApi.Event.Connection.CLOSED, () => {
    Log.e(`Connection to FreeSWITCH was closed. Retrying in ${RETRY_TIMEOUT_IN_MILLIS} millis...`);
    setTimeout(startJob, RETRY_TIMEOUT_IN_MILLIS);
});
```
